---
title: "Feature Group Size"
author: "Steven Pilger"
date: "8/21/2019"
output: 'html_document'
---

```{r}
library(tidyverse)
```
```{r, message=FALSE}
ref_data <- read_csv('../data/signprot_data/amino_acid_features.csv')
```

```{r,message=FALSE}
df <- read_csv('../data/a-gio-features.csv') %>% 
    filter(!is.na(seq_cons)) %>% 
    left_join(ref_data, by = c("feature_code" = "Feature Code", 'length' = 'Sidechain Length')) %>% 
    mutate(aa_group = `Amino Acids`) %>% 
    rowwise() %>% 
    mutate(
        group_size = nchar(paste0(str_split(aa_group, ', ', simplify = T)[1,], collapse = '')),
        segment = str_split(gn, 'x', simplify = T)[,1],
        pos = str_split(gn, 'x', simplify = T)[,2],
        segment = case_when(
            segment == 34 ~ 3.5,
            TRUE ~ as.numeric(segment)
        ),
        cons_ident = case_when(
            str_detect(gn, '3x50|3x53|3x53|34x50|34x51|5x65|5x68|6x29|6x33') ~ TRUE,
            TRUE ~ FALSE,
        )) %>% 
    select(
        feature,
        feature_code,
        length,
        gn,
        pos,
        segment,
        'Interaction Conservation (%)'=freq,
        'Sequence Conservation (%)'=prop_seq_cons,
        # 'Feature Group Size'=group_size
        group_size,
        cons_ident
    ) %>% 
    arrange(segment, pos) %>% 
    rownames_to_column('index') %>% 
    mutate(index = as.integer(index)) %>% 
    gather(
        key,
        val,
        -feature,
        -feature_code,
        -length,
        -index,
        -gn,
        -segment,
        -pos,
        -group_size,
        -cons_ident
    ) %>% 
    mutate(gn = fct_reorder(gn, index))
```

```{r}
plot <- df %>% 
    filter(key=='Interaction Conservation (%)') %>% 
    mutate(group_size = case_when(
        group_size < 3.333 ~ 'small',
        group_size >= 3.333 & group_size <= 6.666 ~ 'medium',
        group_size > 6.666 ~ 'large'
    )) %>% 
    ggplot(aes(gn, val, fill=group_size)) +
    geom_col() +
    geom_point(
        aes(y=3, shape = 8, color=cons_ident),
        size = 3,
        show.legend = FALSE) +
    
    # facet_grid(
    #     key ~ .,
    #     scales = 'free_y',
    #     # space = 'free',
    #     switch = 'both'
    #     ) +
    
    theme_minimal() +
    theme(
        axis.text.x = element_text(angle = 45, hjust = 1),
        # panel.grid.major.x = element_blank(),
        panel.grid.minor.y = element_blank(),
        panel.spacing.y = unit(2, "lines"),
        legend.position = c(1, 1),
        legend.direction = 'horizontal',
        legend.justification = c("right", "top"),
    ) +
    scale_shape_identity() +
    scale_color_manual(
        values = c(NA,'black'),
        guide=FALSE,
        ) +
    scale_fill_brewer(
        'Feature Group Size',
        # limits = c(0,10),
        # breaks = c(2,4,6,8),
        palette = 'Blues',
        direction = -1
        ) +
    labs(
        x='Residue Position',
        y='Interaction Conservation (%)'
    )
    

ggsave(
    '../images/results/a-gio-feature-group-size.pdf',
    plot,
    width = 7,
    height= 5
)

plot
```

```{r,message=FALSE}
df <- read_csv('../data/b1-gs-features.csv') %>% 
    filter(!is.na(seq_cons)) %>% 
    left_join(ref_data, by = c("feature_code" = "Feature Code", 'length' = 'Sidechain Length')) %>% 
    mutate(aa_group = `Amino Acids`) %>% 
    rowwise() %>% 
    mutate(
        group_size = nchar(paste0(str_split(aa_group, ', ', simplify = T)[1,], collapse = '')),
        segment = str_split(gn, 'x', simplify = T)[,1],
        pos = str_split(gn, 'x', simplify = T)[,2],
        segment = case_when(
            segment == 34 ~ 3.5,
            TRUE ~ as.numeric(segment)
        )) %>% 
    select(
        feature,
        feature_code,
        length,
        gn,
        pos,
        segment,
        'Interaction Conservation (%)'=freq,
        'Sequence Conservation (%)'=prop_seq_cons,
        # 'Feature Group Size'=group_size
        group_size
    ) %>% 
    arrange(segment, pos) %>% 
    rownames_to_column('index') %>% 
    mutate(index = as.integer(index)) %>% 
    gather(
        key,
        val,
        -feature,
        -feature_code,
        -length,
        -index,
        -gn,
        -segment,
        -pos,
        -group_size
    ) %>% 
    mutate(gn = fct_reorder(gn, index))
```

```{r}
plot <- df %>% 
    filter(key=='Interaction Conservation (%)') %>% 
    ggplot(aes(gn, val, fill=group_size)) +
    geom_col() +
    
    # facet_grid(
    #     key ~ .,
    #     scales = 'free_y',
    #     # space = 'free',
    #     switch = 'both'
    #     ) +
    
    theme_minimal() +
    theme(
        axis.text.x = element_text(angle = 45, hjust = 1),
        panel.grid.major.x = element_blank(),
        panel.grid.minor.y = element_blank(),
        panel.spacing.y = unit(2, "lines"),
        legend.position = c(1, 1),
        legend.direction = 'horizontal',
        legend.justification = c("right", "top"),
    ) +
    scale_fill_distiller(
        '',
        limits = c(1,10),
        breaks = c(1,10),
        palette = 'Blues',
        direction = 1
        ) +
    labs(
        x='Residue Position',
        y='Interaction Conservation (%)'
    )

ggsave(
    '../images/results/b1-gs-feature-group-size.pdf',
    plot,
    width = 7.5,
    height= 5
)

plot
```

